# Generated by Django 4.2.11 on 2024-04-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('not_say', 'Prefer not to say')], default='not_say', max_length=7),
        ),
    ]
