# Generated by Django 5.0.4 on 2024-04-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csctest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HTMLPage',
            new_name='Exhibits',
        ),
    ]
