# Generated by Django 4.2.11 on 2024-04-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csctest', '0004_exhibit_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeofPlay',
            fields=[
                ('TypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'TypeOfPlay',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ActivityID', models.AutoField(primary_key=True, serialize=False)),
                ('activityName', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ExhibitName', models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='csctest.exhibit')),
                ('category', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.CASCADE, to='csctest.typeofplay')),
            ],
            options={
                'db_table': 'Activities',
            },
        ),
    ]
