# Generated by Django 5.0.4 on 2024-04-18 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csctest', '0004_exhibit_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeofPlay',
            fields=[
                ('TypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'TypeOfPlay',
            },
        ),
        migrations.CreateModel(
            name='PageTimeSpent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048)),
                ('time_spent', models.IntegerField(help_text='Time spent in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ActivityID', models.AutoField(primary_key=True, serialize=False)),
                ('activityName', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.CASCADE, to='csctest.typeofplay')),
            ],
            options={
                'db_table': 'Activities',
            },
        ),
    ]
