# Generated by Django 4.2.11 on 2024-04-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csctest', '0005_typeofplay_activity'),
        ('csctest', '0005_typeofplay_pagetimespent_activity'),
    ]

    operations = [
    ]
