# Generated by Django 4.2.11 on 2024-04-20 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csctest', '0006_merge_20240418_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ExhibitName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csctest.exhibit'),
        ),
    ]
