# Generated by Django 4.2.11 on 2024-04-21 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_chatbotresponse'),
        ('csctest', '0007_alter_activity_exhibitname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ExhibitName',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ExhibitRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.child')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csctest.exhibit')),
            ],
            options={
                'unique_together': {('child', 'exhibit')},
            },
        ),
    ]
